name: Build and Deploy

on:
  workflow_dispatch:
    inputs:
      trigger_build:
        description: 'Should the build job run?'
        required: true
        default: true  # Default is true, meaning build job will run unless explicitly set to false
        type: boolean

      trigger_deploy:
        description: 'Should the deploy job run?'
        required: true
        default: true  # Default is true, meaning deploy job will run unless explicitly set to false
        type: boolean

  pull_request:
    types:
      - closed  # Run when PR is merged

  push:
    branches:
      - main
      - dev
      - feature/*
    paths:
      - src/**
      - package.json
      - package-lock.json
      - .github/workflows/**

permissions:
  pages: write      # to deploy to Pages
  id-token: write   # to verify the deployment originates from an appropriate source
  contents: write

env:
  WORKING_DIRECTORY: ./
  ARTIFACT_NAME: angular-build

jobs:
  build:
    if: github.event_name != 'workflow_dispatch' || github.event.inputs.trigger_build == 'true'  # Runs if triggered manually or input is true
    runs-on: ubuntu-latest

    outputs:
      artifact-name:  ${{ env.ARTIFACT_NAME }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies
        run: npm install
        working-directory: ${{ env.WORKING_DIRECTORY }}

      - name: Build Angular app
        run: npm run build
        working-directory: ${{ env.WORKING_DIRECTORY }}
      

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist/ul-portfolio
          branch: prod  
          token: ${{ secrets.GITHUB_TOKEN }}
      
