name: Build and Deploy

on:
  workflow_dispatch:
    inputs:
      trigger_build:
        description: "Build?"
        required: true
        default: true # Default is true, meaning build job will run unless explicitly set to false
        type: boolean

      trigger_deploy:
        description: "Deploy?"
        required: true
        default: false # Default is true, meaning deploy job will run unless explicitly set to false
        type: boolean

  push:
    branches:
      - main
      - dev
      - feature/*
    paths:
      - src/**
      - package.json
      - package-lock.json
      - .github/workflows/**

env:
  WORKING_DIRECTORY: ./
  OUTPUT_PATH: dist/ul-portfolio/browser
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  build:
    if: github.event_name != 'workflow_dispatch' || github.event.inputs.trigger_build == 'true' # Runs if triggered manually or input is true
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Set up Node.js
        uses: actions/setup-node@v6
        with:
          node-version: "25.x"
          cache: "npm"
          cache-dependency-path: package-lock.json

      - name: Install dependencies
        id: install
        run: npm ci
        working-directory: ${{ env.WORKING_DIRECTORY }}

      - name: Run lint
        id: lint
        run: npm run lint
        working-directory: ${{ env.WORKING_DIRECTORY }}

      - name: Run tests
        id: test
        run: npm test
        working-directory: ${{ env.WORKING_DIRECTORY }}

      - name: Build Angular app
        id: build
        run: npm run build
        working-directory: ${{ env.WORKING_DIRECTORY }}

      - name: Clone index.html to 404.html for Angular 17+
        id: copy
        run: |
          cp ${{ env.OUTPUT_PATH }}/index.html ${{ env.OUTPUT_PATH }}/404.html
          echo -e "\033[0;32mSuccessfully cloned index.html to 404.html\033[0m"
        working-directory: ${{ env.WORKING_DIRECTORY }}

      - name: Upload build artifact
        id: deployment
        uses: actions/upload-pages-artifact@v4
        with:
          path: ${{ env.OUTPUT_PATH }}

  deploy:
    if: >
      (github.event_name == 'workflow_dispatch' && github.event.inputs.trigger_deploy == 'true') ||
      (github.ref == 'refs/heads/main')
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build # Ensures deploy happens only after the build

    permissions:
      pages: write # to deploy to Pages
      id-token: write # to verify the deployment originates from an appropriate source

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
