name: Build and Deploy

on:
  workflow_dispatch:
    inputs:
      trigger_build:
        description: "Build?"
        required: true
        default: true # Default is true, meaning build job will run unless explicitly set to false
        type: boolean

      trigger_deploy:
        description: "Deploy?"
        required: true
        default: false # Default is true, meaning deploy job will run unless explicitly set to false
        type: boolean

  pull_request:
    types:
      - closed # Run when PR is merged

  push:
    branches:
      - main
      - dev
      - feature/*
    paths:
      - src/**
      - package.json
      - package-lock.json
      - .github/workflows/**

env:
  WORKING_DIRECTORY: ./
  ARTIFACT_NAME: ul-portfolio
  OUTPUT_PATH: dist/ul-portfolio/browser

jobs:
  build:
    if: github.event_name != 'workflow_dispatch' || github.event.inputs.trigger_build == 'true' # Runs if triggered manually or input is true
    runs-on: ubuntu-latest

    outputs:
      artifact-name: ${{ env.ARTIFACT_NAME }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"
          registry-url: "https://registry.npmjs.org"

      - name: Install dependencies
        run: npm install
        working-directory: ${{ env.WORKING_DIRECTORY }}

      - name: Build Angular app
        run: npm run build
        working-directory: ${{ env.WORKING_DIRECTORY }}
      
      - name: Clone index.html to 404.html for Angular 17+
        run: cp ${{ env.OUTPUT_PATH }}/index.html ${{ env.OUTPUT_PATH }}/404.html
        working-directory: ${{ env.WORKING_DIRECTORY }}

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.ARTIFACT_NAME }}
          path: dist/
          retention-days: 7

  deploy:
    if: >
      (github.event_name == 'workflow_dispatch' && github.event.inputs.trigger_deploy == 'true') ||
      (github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged == true)

    runs-on: ubuntu-latest
    needs: build # Ensures deploy happens only after the build

    permissions:
      contents: write # This gives write access to repository contents (enabling pushing to gh-pages)
      pull-requests: write # This can be useful if you need PR permissions as well (optional)
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: ${{ env.ARTIFACT_NAME }}
          path: dist/

      - name: Debug dist folder
        run: ls -R dist/

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: ${{ env.OUTPUT_PATH }}
          clean: true # Ensure previous deployment folder is cleaned up before deployment
          force: true # Force push the changes even if there are conflicts
