name: Deploy to GitHub Pages

on:
  pull_request:
    types:
      - closed # Run when a PR is merged
  workflow_dispatch: # Allow manual deploy trigger

jobs:
  deploy:
    if: github.event.pull_request.merged == true || github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download latest build artifact
        uses: actions/download-artifact@v4
        with:
          name: angular-build
          path: dist/

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: dist/
